# noqa: E501
"""Catálogo extra de Clínica Médica — estilo prova de residência (CM forte)."""

CM_WAVE2 = [
    ("Tireoide", "Crise tireotóxica", "avancado",
     "{{sexWord}} de {{age}} com FA, febre e Burch-Wartofsky alto. Conduta?",
     "Suporte, betabloqueador, tionamida, iodo após tionamida e corticoide; tratar gatilho",
     "Iodo antes da tionamida e alta ambulatorial", "ATA thyrotoxicosis"),
    ("Tireoide", "Mixedema", "avancado",
     "{{sexWord}} de {{age}} com hipotermia, bradicardia e coma. Conduta?",
     "UTI, T4 IV (± T3), corticoide até excluir insuficiência adrenal e suporte",
     "Apenas aquecimento sem reposição hormonal", "ATA myxedema"),
    ("Tireoide", "Hipotireoidismo", "basico",
     "{{sexWord}} de {{age}} com TSH {{tsh}} e T4 livre baixo. Conduta?",
     "Iniciar levotiroxina e reavaliar TSH em 6–8 semanas",
     "Iodo radioativo como primeira linha do hipotireoidismo primário", "ATA hypothyroidism",
     {"tsh": 28}),
    ("Tireoide", "Nódulo", "intermediario",
     "{{sexWord}} de {{age}} com nódulo tireoidiano e Tirads alto. Conduta?",
     "PAAF conforme risco ecográfico/tamanho; TSH e seguimento estruturado",
     "Tireoidectomia total em todo nódulo sem PAAF", "ATA nodules"),
    ("Adrenal", "Insuficiência aguda", "avancado",
     "{{sexWord}} de {{age}} com choque, hiponatremia e hiperK sob estresse. Conduta?",
     "Hidrocortisona IV + volume imediatamente — não atrasar por cortisol basal",
     "Aguardar ACTH stim completo antes de qualquer esteroide", "Endocrine Society AI"),
    ("Adrenal", "Cushing", "avancado",
     "{{sexWord}} de {{age}} com obesidade central, pletora e cortisol livre urinário alto. Conduta?",
     "Confirmar hipercortisolismo e depois diferenciar ACTH-dependente vs independente",
     "Adrenalectomia bilateral empírica sem confirmação", "Endocrine Society Cushing"),
    ("Adrenal", "Incidentaloma", "intermediario",
     "{{sexWord}} de {{age}} com massa adrenal de 2,5 cm em TC. Conduta?",
     "Avaliar funcionalidade (aldo/cortisol/metanefrinas) e características de imagem",
     "Ignorar e nunca dosar hormônios", "AACE adrenal"),
    ("Paratireoide", "HiperPTH", "intermediario",
     "{{sexWord}} de {{age}} com Ca alto, PTH alto e TFG estável. Conduta?",
     "Confirmar hiperparatireoidismo primário e avaliar critérios cirúrgicos/densidade óssea",
     "Apenas restrição extrema de cálcio sem investigação", "AAES PHPT"),
    ("Paratireoide", "Hipocalcemia", "intermediario",
     "{{sexWord}} de {{age}} pós-tireoidectomia com formigamento e Ca baixo. Conduta?",
     "Reposição de cálcio ± calcitriol e monitorar; IV se grave/sintomático",
     "Bifosfonato IV na hipocalcemia aguda pós-cirúrgica", "ATA hypocalcemia"),
    ("Osteoporose", "Fratura", "basico",
     "{{sexWord}} de {{age}} com fratura de fêmur por fragilidade. Conduta?",
     "Tratar causa, cálcio/vit D e anti-reabsortivo/anabólico conforme risco",
     "Apenas analgésico sem prevenção de nova fratura", "AACE osteoporosis"),
    ("DM", "Hipoglicemia grave", "intermediario",
     "{{sexWord}} de {{age}} diabético inconsciente com glicemia 38. Conduta?",
     "Glicose IV (ou glucagon se sem acesso) e investigar causa; ajustar esquema",
     "Insulina adicional para “corrigir” a hipoglicemia", "ADA hypoglycemia"),
    ("DM", "Pé diabético", "intermediario",
     "{{sexWord}} de {{age}} com úlcera plantar e sinais de infecção. Conduta?",
     "Desbridamento, ATB se infecção, alívio de pressão e avaliar vascular/osteomielite",
     "Apenas pomada caseira sem avaliação", "IWGDF"),
    ("DM", "Retinopatia", "basico",
     "{{sexWord}} de {{age}} com DM2 há 8 anos sem fundo de olho. Conduta?",
     "Rastrear retinopatia e otimizar glicemia/PA; referir se lesão",
     "Nunca rastrear fundo de olho no DM2", "ADA retinopathy"),
    ("DM", "Neuropatia", "basico",
     "{{sexWord}} de {{age}} com queimação nos pés e monofilamento alterado. Conduta?",
     "Otimizar glicemia, cuidar dos pés e tratar dor neuropática se presente",
     "Amputação profilática bilateral de rotina", "ADA neuropathy"),
    ("Obesidade", "Farmacoterapia", "intermediario",
     "{{sexWord}} de {{age}} com IMC 34 e comorbidades após falha de estilo de vida. Conduta?",
     "Considerar farmacoterapia antiobesidade aprovada + manutenção de hábitos",
     "Cirurgia bariátrica obrigatória em todo IMC 30 sem tentativa clínica", "AACE obesity"),
    ("Obesidade", "Bariátrica", "avancado",
     "{{sexWord}} de {{age}} com IMC 42 e DM2 mal controlado. Conduta?",
     "Avaliar cirurgia metabólica em centro experiente após preparo multidisciplinar",
     "Contraindicar qualquer cirurgia só pelo diagnóstico de DM2", "ASMBS"),
    ("Lipídios", "Hipertrigliceridemia", "intermediario",
     "{{sexWord}} de {{age}} com TG {{tg}} e dor abdominal. Conduta?",
     "Suspender triglicérides orais de risco, volume, insulina/heparina se indicado e fibrato após estabilizar",
     "Estatina isolada como tratamento agudo de TG 2000 com pancreatite", "Endocrine Society lipids",
     {"tg": 1800}),
    ("Lipídios", "Risco alto", "basico",
     "{{sexWord}} de {{age}} com LDL 190 sem causa secundária. Conduta?",
     "Estatina de alta intensidade e investigar hipercolesterolemia familiar",
     "Apenas fitoterápico sem estatina", "ESC lipids"),
    ("Gota", "Crise", "basico",
     "{{sexWord}} de {{age}} com podagra e sem contraindicação. Conduta aguda?",
     "AINE, colchicina ou corticoide — escolher conforme comorbidades",
     "Alopurinol em dose alta no pico da crise como única medida", "ACR gout"),
    ("Gota", "Profilaxia", "intermediario",
     "{{sexWord}} de {{age}} com gota tofácea recorrente. Conduta de fundo?",
     "Iniciar hipouricemiante com profilaxia anti-crise e titular ao alvo de ácido úrico",
     "Nunca usar alopurinol/febuxostate mesmo com tofos", "ACR gout"),
    ("AR", "Diagnóstico", "intermediario",
     "{{sexWord}} de {{age}} com poliartrite simétrica >6 semanas e FR/ACPA+. Conduta?",
     "Iniciar DMARD precoce (ex. metotrexato) + avaliação reumatológica",
     "Apenas opioide crônico sem DMARD", "ACR RA"),
    ("LES", "Flare cutâneo-articular", "intermediario",
     "Mulher de {{age}} com LES, rash e artrite sem nefrite. Conduta?",
     "Hidroxicloroquina base; ajustar imunossupressão conforme gravidade e evitar sol",
     "Ciclofosfamida IV de rotina em todo rash malar", "EULAR SLE"),
    ("Esclerose", "Crise renal", "avancado",
     "{{sexWord}} de {{age}} com esclerodermia, PA alta e LRA. Conduta?",
     "IECA agressivo (mesmo com Cr alta) — crise renal esclerodérmica",
     "Corticoide em megadose como primeira linha isolada", "EULAR SSc"),
    ("Vasculite", "Horton", "avancado",
     "{{sexWord}} de {{age}} com cefaleia nova, claudicação mandibular e VHS alto. Conduta?",
     "Corticoide imediato para proteger visão e biópsia/imagem sem atrasar tratamento",
     "Esperar biópsia negativa para iniciar corticoide", "EULAR GCA"),
    ("Miastenia", "Crise", "avancado",
     "{{sexWord}} de {{age}} com miastenia e insuficiência respiratória. Conduta?",
     "UTI, suporte ventilatório, PLEX/IVIG e revisar gatilhos/medicamentos",
     "Betabloqueador e aminoglicosídeo liberados na crise", "MGFA"),
    ("Parkinson", "Quedas", "intermediario",
     "{{sexWord}} de {{age}} com Parkinson e quedas. Conduta?",
     "Ajustar terapia dopaminérgica, fisioterapia e revisar fármacos que pioram equilíbrio",
     "Haloperidol de rotina para “acalmar”", "MDS Parkinson"),
    ("Demência", "Investigação", "basico",
     "{{sexWord}} de {{age}} com declínio cognitivo progressivo. Conduta inicial?",
     "História, exame, TSH/B12/imagem e rastrear depressão/delirium reversíveis",
     "Diagnóstico de Alzheimer só pela idade sem avaliação", "AAN dementia"),
    ("Delirium", "Hospitalar", "intermediario",
     "{{sexWord}} de {{age}} confuso no 2º dia de internação. Conduta?",
     "Tratar causa (infecção/dor/retenção/meds), orientar e evitar contenção/benzo de rotina",
     "Midazolam contínuo como primeira linha do delirium", "NICE delirium"),
    ("Enxaqueca", "Abortiva", "basico",
     "{{sexWord}} de {{age}} com migrânea típica sem aura grave. Conduta aguda?",
     "AINE/triptano precoce conforme perfil; antiemético se náusea",
     "Opioide de rotina em toda crise de enxaqueca", "AHS migraine"),
    ("Enxaqueca", "Profilaxia", "intermediario",
     "{{sexWord}} de {{age}} com >8 dias de migrânea/mês. Conduta?",
     "Profilaxia (beta/antiepiléptico/antidepressivo/anti-CGRP) + diário de crises",
     "Apenas analgesia de resgate diária sem profilaxia", "AHS prevention"),
    ("Epilepsia", "1ª crise", "intermediario",
     "{{sexWord}} de {{age}} após primeira crise não provocada. Conduta?",
     "Investigar gatilho, EEG/imagem; ASE se alto risco de recorrência",
     "Negar qualquer investigação após convulsão", "ILAE"),
    ("AVC", "Secundária", "basico",
     "{{sexWord}} de {{age}} pós-AVC isquêmico estável. Prevenção?",
     "Antiagregante (ou anticoag se FA), estatina, PA e estilo de vida",
     "Nenhuma prevenção secundária após AVC", "AHA secondary stroke"),
    ("AIT", "Alto risco", "avancado",
     "{{sexWord}} de {{age}} com AIT e ABCD2 alto. Conduta?",
     "Investigação urgente (imagem vascular/cardio) e antiagregante precoce",
     "Retorno eletivo em 3 meses sem investigação", "AHA TIA"),
    ("Parkinsonismo", "Fármaco", "intermediario",
     "{{sexWord}} de {{age}} com rigidez após metoclopramida. Conduta?",
     "Suspender o fármaco ofensor e tratar sintomas se preciso",
     "Aumentar a dose de metoclopramida", "Drug-induced parkinsonism"),
    ("Esclerose múltipla", "Surto", "avancado",
     "{{sexWord}} de {{age}} com déficit neurológico novo e lesões típicas. Conduta do surto?",
     "Corticoide em altas doses se déficit funcional e avaliar DMT",
     "Antibiótico isolado como tratamento do surto demielinizante", "AAN MS"),
    ("Meningite", "Listeria", "avancado",
     "{{sexWord}} de {{age}} >50 anos com meningite bacteriana. Empírico?",
     "Cobrir Listeria (ampicilina) além de pneumococo/meningococo conforme protocolo",
     "Apenas azitromicina oral", "IDSA meningitis"),
    ("Encefalite", "HSV", "avancado",
     "{{sexWord}} de {{age}} com febre, confusão e temporal na RM. Conduta?",
     "Aciclovir IV precoce sem atrasar por PCR se alta suspeita",
     "Esperar PCR negativa para iniciar aciclovir", "IDSA encephalitis"),
    ("HIV", "Infecção aguda", "intermediario",
     "{{sexWord}} de {{age}} com síndrome mono-like e risco sexual. Conduta?",
     "Teste Ag/Ab + carga viral se suspeita aguda; orientar PrEP/PEP conforme janela",
     "Negar HIV porque ELISA antigo foi negativo há 1 ano", "CDC HIV"),
    ("HIV", "Oportunista", "avancado",
     "{{sexWord}} de {{age}} com HIV, CD4 40 e pneumonia hipoxêmica. Conduta?",
     "Tratar Pneumocystis (TMP-SMX ± corticoide se hipoxemia) e iniciar TARV no tempo certo",
     "Apenas oxigênio sem antimicrobiano específico", "DHHS OI"),
    ("TB", "Pulmonar", "intermediario",
     "{{sexWord}} de {{age}} com tosse >3 semanas, emagrecimento e BAAR+. Conduta?",
     "Notificar e iniciar esquema RIPE supervisionado; isolar conforme protocolo",
     "Azitromicina 3 dias e alta sem notificação", "MS TB"),
    ("TB", "Latente", "basico",
     "{{sexWord}} de {{age}} contato de bacilífero com IGRA+. Conduta?",
     "Tratar infecção latente após excluir doença ativa",
     "RIPE completo sem avaliar se há doença ativa", "CDC LTBI"),
    ("COVID", "Grave", "intermediario",
     "{{sexWord}} de {{age}} com COVID, Sat 88% e necessidade de O2. Conduta?",
     "O2, corticoide se hipoxêmico, tromboprofilaxia e cuidados de suporte",
     "Ivermectina + altas doses de vitamina C como padrão-ouro", "NIH COVID"),
    ("Influenza", "Risco", "basico",
     "{{sexWord}} de {{age}} com síndrome gripal e comorbidade. Conduta?",
     "Oseltamivir precoce se indicado + suporte; vacinar na prevenção",
     "Antibiótico de amplo espectro em toda gripe sem complicação", "CDC influenza"),
    ("Dengue", "Alarme", "intermediario",
     "{{sexWord}} de {{age}} com dengue, dor abdominal e hemoconcentração. Conduta?",
     "Hidratação criteriosa, vigilância de choque e evitar AINE",
     "AAS pleno e alta imediata", "MS dengue"),
    ("Leptospirose", "Icterícia", "avancado",
     "{{sexWord}} de {{age}} com febre, mialgia de panturrilha e icterícia pós-enchente. Conduta?",
     "ATB precoce (penicilina/doxiciclina/ceftriaxona conforme gravidade) e suporte",
     "Apenas repouso sem antimicrobiano na forma ictérica", "MS leptospirose"),
    ("Malária", "Falciparum", "avancado",
     "{{sexWord}} de {{age}} febril após área endêmica com gota espessa+. Conduta?",
     "Tratamento antimalárico imediato conforme espécie/gravidade e suporte",
     "Aguardar hemocultura negativa por 1 semana", "WHO malaria"),
    ("Sífilis", "Secundária", "intermediario",
     "{{sexWord}} de {{age}} com rash palmoplantar e VDRL alto. Conduta?",
     "Penicilina benzatina conforme estágio; tratar parceiros e notificar",
     "Apenas corticoide tópico no rash", "CDC syphilis"),
    ("Gonorreia", "Uretrite", "basico",
     "{{sexWord}} de {{age}} com secreção uretral purulenta. Conduta?",
     "Ceftriaxona (± cobertura de clamídia conforme protocolo) e tratar parceiro",
     "Apenas fluconazol oral", "CDC STI"),
    ("Celulite", "Não purulenta", "basico",
     "{{sexWord}} de {{age}} com eritema quente em membro sem abscesso. Conduta?",
     "ATB cobrindo estreptococo/MSSA e elevar membro; avaliar gravidade",
     "Drenagem cirúrgica obrigatória sem coleção", "IDSA SSTI"),
    ("Abscesso", "Drenagem", "basico",
     "{{sexWord}} de {{age}} com abscesso cutâneo flutuante. Conduta?",
     "Incisão e drenagem; ATB se celulite/sistema ou imunossupressão",
     "Só ATB oral sem drenar coleção", "IDSA SSTI"),
    ("Osteomielite", "Crônica", "avancado",
     "{{sexWord}} de {{age}} com úlcera profunda e osso exposto. Conduta?",
     "Imagem, cultura óssea se possível, ATB prolongado e avaliação cirúrgica",
     "Pomada tópica por 3 dias como cura", "IDSA osteomyelitis"),
    ("Endocardite", "Profilaxia", "intermediario",
     "{{sexWord}} de {{age}} com prótese valvar antes de procedimento dental invasivo. Conduta?",
     "Profilaxia antibiótica conforme indicação de alto risco",
     "Profilaxia em todo paciente saudável para qualquer procedimento", "AHA IE prophylaxis"),
    ("Pneumonia", "Aspiração", "intermediario",
     "{{sexWord}} de {{age}} com AVC e infiltrado em segmento dependente. Conduta?",
     "ATB cobrindo anaeróbios se indicado, suporte e prevenção de nova aspiração",
     "Corticoides inalatórios isolados como tratamento", "IDSA aspiration"),
    ("Derrame", "Parapneumônico", "avancado",
     "{{sexWord}} de {{age}} com pneumonia e derrame septado. Conduta?",
     "Drenagem + ATB; avaliar fibrinolítico/cirurgia se loculado",
     "Observar sem drenar empiema organizado", "BTS pleural"),
    ("Asma", "Degrau", "intermediario",
     "{{sexWord}} de {{age}} com asma não controlada em CI baixa. Conduta?",
     "Subir degrau (CI/LABA), revisar técnica/adesão e gatilhos",
     "Suspender CI e deixar só SABA", "GINA"),
    ("DPOC", "Oxigenoterapia", "avancado",
     "{{sexWord}} de {{age}} com DPOC e PaO2 52 em ar ambiente estável. Conduta?",
     "Oxigenoterapia domiciliar contínua se critérios; alvo 88–92%",
     "O2 a 15 L liberado sem alvo na DPOC crônica", "GOLD"),
    ("SAOS", "CPAP", "intermediario",
     "{{sexWord}} de {{age}} obeso com sonolência e IAH alto. Conduta?",
     "CPAP + perda de peso e avaliar risco cardiovascular",
     "Benzodiazepínico noturno como primeira linha", "AASM OSA"),
    ("TEP", "Baixo risco", "basico",
     "{{sexWord}} de {{age}} com TEP pequeno, estável, sem VD. Conduta?",
     "Anticoagulação e avaliar ambulatorização selecionada",
     "Trombólise de rotina em todo TEP de baixo risco", "ESC PE"),
    ("TVP", "Câncer", "avancado",
     "{{sexWord}} de {{age}} com câncer ativo e TVP. Conduta?",
     "Anticoagular (DOAC ou HBPM conforme cenário) por ≥3–6 meses",
     "Apenas AAS no câncer associado a TVP", "ASH VTE cancer"),
    ("IC", "Descompensação", "intermediario",
     "{{sexWord}} de {{age}} com IC, ganho de peso e edema. Conduta?",
     "Intensificar diurético, revisar precipitantes e otimizar terapia de base",
     "Suspender toda a quádrupla na descompensação leve", "ESC HF"),
    ("IC", "Ferro", "intermediario",
     "{{sexWord}} de {{age}} com ICFER e deficiência de ferro. Conduta?",
     "Considerar ferro IV para sintomas/reduzir hospitalização conforme evidência",
     "Ignorar ferro porque a Hb está “no limite baixo”", "ESC HF iron"),
    ("IAM", "Complicação", "avancado",
     "{{sexWord}} de {{age}} pós-IAM com sopro novo e choque. Conduta?",
     "Suspeitar CIV/IM aguda: estabilizar e cirurgia/intervenção urgente",
     "Alta com AAS apenas", "ESC STEMI complications"),
    ("Pericárdio", "Tamponamento", "avancado",
     "{{sexWord}} de {{age}} com turgência jugular, hipotensão e pulso paradoxal. Conduta?",
     "Ecocardiograma e pericardiocentese urgente se tamponamento",
     "Diurético de alça agressivo como única medida", "ESC pericardial"),
    ("Valva", "IM aguda", "avancado",
     "{{sexWord}} de {{age}} com EAP e sopro sistólico novo pós-IAM. Conduta?",
     "Suporte, vasodilatação se PA permitir e avaliação cirúrgica urgente",
     "Exercício de esforço diagnóstico imediato", "ESC valvular"),
    ("Aorta", "Dissecção", "avancado",
     "{{sexWord}} de {{age}} com dor torácica lacerante e assimetria de PA. Conduta?",
     "Controle de PA/FC e TC/TEE urgente; cirurgia se tipo A",
     "Trombólise empírica sem imagem", "AHA aortic"),
    ("HDA", "Úlcera", "intermediario",
     "{{sexWord}} de {{age}} com melena, PA 100/60. Conduta?",
     "ABC, reposição, IBP IV e endoscopia precoce",
     "Colonoscopia como primeiro exame na melena típica", "ACG UGIB"),
    ("HDB", "Instável", "avancado",
     "{{sexWord}} de {{age}} com enterorragia maciça e choque. Conduta?",
     "Reanimação, localizar sangramento (angio/endoscopia) e hemostasia",
     "Alta com fibras alimentares", "ACG LGIB"),
    ("DII", "Retocolite grave", "avancado",
     "{{sexWord}} de {{age}} com RCU, >10 evacuações e taquicardia. Conduta?",
     "Internar, corticoide IV, tromboprofilaxia e resgate/cirurgia se refratário",
     "AINE + alta ambulatorial", "ECCO UC"),
    ("DII", "Crohn fistula", "avancado",
     "{{sexWord}} de {{age}} com Crohn e fístula perianal. Conduta?",
     "ATB, drenagem se abscesso e terapia biológica/cirurgia conforme extensão",
     "Apenas laxativo osmótico", "ECCO Crohn"),
    ("Doença celíaca", "Diagnóstico", "intermediario",
     "{{sexWord}} de {{age}} com diarreia crônica e anti-tTG IgA alto. Conduta?",
     "Confirmar com biópsia (se indicado) e dieta sem glúten com nutricionista",
     "Dieta sem glúten sem investigação e sem IgA total", "ACG celiac"),
    ("SII", "Diagnóstico", "basico",
     "{{sexWord}} de {{age}} com dor relacionada a evacuação sem alarmes. Conduta?",
     "Critérios de Roma, educar, fibra/soluble e tratar subtipo; investigar alarmes",
     "Colonoscopia anual obrigatória em todo SII jovem sem alarmes", "ACG IBS"),
    ("Hepatite", "B crônica", "avancado",
     "{{sexWord}} de {{age}} HBsAg+ com ALT alta e carga viral elevada. Conduta?",
     "Avaliar fibrose e tratar com análogo (tenofovir/entecavir) se indicado",
     "Interferon + álcool liberado", "AASLD HBV"),
    ("Hepatite", "C", "intermediario",
     "{{sexWord}} de {{age}} com anti-HCV+ e RNA detectável. Conduta?",
     "Tratar com AAD pangenotípico conforme esquema e avaliar fígado",
     "Observar eternamente sem antivirais modernos", "AASLD HCV"),
    ("Cirrose", "Varizes", "intermediario",
     "{{sexWord}} de {{age}} cirrótico com varizes grandes na EDA. Conduta?",
     "Betabloqueador não seletivo ou ligadura conforme cenário",
     "AAS como profilaxia de sangramento varicoso", "Baveno"),
    ("Cirrose", "CHC rastreio", "basico",
     "{{sexWord}} de {{age}} com cirrose compensada. Rastreio?",
     "US (± AFP) a cada 6 meses para carcinoma hepatocelular",
     "Nunca rastrear CHC na cirrose", "AASLD HCC"),
    ("Pancreatite", "Necrose infectada", "avancado",
     "{{sexWord}} de {{age}} com pancreatite e piora tardia, gás na TC. Conduta?",
     "ATB + abordagem step-up (dreno/necrosectomia) em centro experiente",
     "Alta com dieta absoluta eterna sem imagem", "IAP/APA"),
    ("Colelitíase", "Cólica", "basico",
     "{{sexWord}} de {{age}} com cólica biliar e US com cálculos. Conduta?",
     "Analgesia e colecistectomia eletiva se sintomática",
     "ATB crônico como cura definitiva dos cálculos", "Tokyo"),
    ("Colangite", "Tokyo", "avancado",
     "{{sexWord}} de {{age}} com febre, icterícia e dor em HD. Conduta?",
     "ATB + descompressão biliar urgente (CPRE) na colangite",
     "Apenas antiemético oral", "Tokyo cholangitis"),
    ("Anemia", "B12", "basico",
     "{{sexWord}} de {{age}} com VCM alto, formigamento e B12 baixa. Conduta?",
     "Reposição de B12 e investigar causa (IF, dieta, fármacos)",
     "Ferro IV como tratamento da deficiência de B12", "ASH B12"),
    ("Anemia", "Hemolítica", "avancado",
     "{{sexWord}} de {{age}} com anemia, LDH alta, bilirrubina indireta e haptoglobina baixa. Conduta?",
     "Confirmar hemolise, Coombs e tratar conforme etiologia",
     "Transfundir sem investigação em todo caso estável", "ASH hemolysis"),
    ("PTT", "Suspeita", "avancado",
     "{{sexWord}} de {{age}} com MAHA, plaquetopenia e neurológico. Conduta?",
     "PLEX urgente + corticoide; caplacizumab conforme protocolo — não esperar ADAMTS13",
     "Apenas AAS e observação", "ISTH TTP"),
    ("PTI", "Sangramento", "intermediario",
     "{{sexWord}} de {{age}} com PTI e sangramento mucoso, plaq 8 mil. Conduta?",
     "Corticoide ± IgIV e avaliar necessidade de transfusão de plaqueta se grave",
     "Esplenectomia no pronto-socorro em todo PTI novo", "ASH ITP"),
    ("Neutropenia febril", "Urgência", "avancado",
     "{{sexWord}} de {{age}} oncológico com neutrófilos 200 e febre. Conduta?",
     "Hemoculturas e ATB de amplo espectro imediato",
     "Esperar culturas por 48 h sem ATB", "IDSA FN"),
    ("TEV", "Profilaxia hospitalar", "basico",
     "{{sexWord}} de {{age}} internado clínico de alto risco. Conduta?",
     "Profilaxia farmacológica (ou mecânica se sangramento) conforme risco",
     "Nenhuma profilaxia em alto risco imobilizado", "ASH prophylaxis"),
    ("Asma", "Gestação", "intermediario",
     "Gestante de {{age}} com asma sintomática. Conduta?",
     "Manter CI (± LABA) — controlar asma protege o feto; evitar SABA isolado crônico",
     "Suspender todos os inalatórios na gestação", "GINA pregnancy"),
    ("Trombo", "Gestação", "avancado",
     "Gestante de {{age}} com TVP confirmada. Conduta?",
     "HBPM na gestação; evitar DOAC/varfarina (exceto cenários específicos de valva)",
     "Varfarina livre no 1º trimestre de rotina", "ACOG VTE"),
    ("HAS", "Resistente", "avancado",
     "{{sexWord}} de {{age}} com PA alta em 3 classes na dose máxima. Conduta?",
     "Confirmar adesão/MAPA, otimizar diurético e investigar secundárias",
     "Adicionar mais 5 anti-hipertensivos sem reavaliar adesão", "AHA resistant HTN"),
    ("HAS", "Secundária", "intermediario",
     "{{sexWord}} de {{age}} jovem com HAS súbita e hipocalemia. Conduta?",
     "Investigar hiperaldosteronismo e outras causas secundárias",
     "Ignorar K baixo e só aumentar tiazídico", "Endocrine Society PA"),
    ("Rinite", "Alérgica", "basico",
     "{{sexWord}} de {{age}} com espirros sazonais e coriza. Conduta?",
     "Corticoide nasal ± anti-histamínico e controle ambiental",
     "ATB de amplo espectro em toda rinite alérgica", "ARIA"),
    ("Sinusite", "Bacteriana", "intermediario",
     "{{sexWord}} de {{age}} com sinusite >10 dias ou piora bipásica. Conduta?",
     "ATB se critérios bacterianos; corticóide nasal e analgesia",
     "TC imediata e cirurgia em toda sinusite viral", "IDSA sinusitis"),
    ("Faringite", "Estrepto", "basico",
     "{{sexWord}} de {{age}} com Centor alto e teste estrepto+. Conduta?",
     "Penicilina/amoxicilina conforme protocolo e sintomáticos",
     "Ciprofloxacino de rotina na faringite estreptocócica", "IDSA pharyngitis"),
    ("Otite", "Externa", "basico",
     "{{sexWord}} de {{age}} com dor à tração do pavilhão e conduto edemaciado. Conduta?",
     "Analgesia e gotas otológicas com cobertura adequada; evitar irrigação se perfuração",
     "ATB IV de rotina em toda otite externa simples", "AAO-HNS"),
    ("Glaucoma", "Agudo", "avancado",
     "{{sexWord}} de {{age}} com olho vermelho, dor e pupila média fixa. Conduta?",
     "Emergência oftalmológica — baixar PIO e avaliar iridotomia",
     "Corticoide tópico isolado sem avaliar PIO", "AAO glaucoma"),
    ("Cefaleia", "Alarme", "avancado",
     "{{sexWord}} de {{age}} com “pior cefaleia da vida” súbita. Conduta?",
     "TC ± punção para hemorragia subaracnóide — não tratar como enxaqueca",
     "Alta com dipirona sem imagem", "AHA SAH"),
    ("Intoxicação", "Paracetamol", "avancado",
     "{{sexWord}} de {{age}} com ingestão de paracetamol e ALT em ascensão. Conduta?",
     "N-acetilcisteína conforme nomograma/risco e suporte hepático",
     "Apenas carvão 24 h após sem NAC", "Poison control APAP"),
    ("Intoxicação", "Opioide", "basico",
     "{{sexWord}} de {{age}} com miose, bradipneia e coma. Conduta?",
     "ABC e naloxona titulada; observar recidiva",
     "Flumazenil como antídoto do opioide", "ACLS opioid"),
    ("Intoxicação", "Benzodiazepínico", "intermediario",
     "{{sexWord}} de {{age}} sedado por benzo, estável respiratório. Conduta?",
     "Suporte; flumazenil só em selecionados (risco de crise)",
     "Flumazenil em massa em todo usuário crônico de benzo", "Poison benzo"),
    ("Queimadura", "Fluido", "avancado",
     "{{sexWord}} de {{age}} com queimadura extensa. Conduta inicial?",
     "ABC, Parkland/ajuste por meta urinária e cobrir feridas; transferir se critério",
     "Restringir volume agressivamente sem monitorar diurese", "ABA burn"),
    ("Anafilaxia", "Observação", "intermediario",
     "{{sexWord}} de {{age}} após adrenalina por anafilaxia. Conduta?",
     "Observar risco bifásico, prescrever autoinjetor e investigar gatilho",
     "Alta em 10 minutos sem educação nem autoinjetor", "WAO"),
    ("Urticária", "Aguda", "basico",
     "{{sexWord}} de {{age}} com urticária sem anafilaxia. Conduta?",
     "Anti-histamínico de 2ª geração; investigar gatilho; adrenalina se progressão sistêmica",
     "ATB de amplo espectro em toda urticária", "EAACI urticaria"),
    ("Dermatite", "Contato", "basico",
     "{{sexWord}} de {{age}} com eczema em área de contato com níquel. Conduta?",
     "Evitar alérgeno, corticoide tópico e emolientes",
     "Ciclosporina oral imediata em toda dermatite leve", "AAD dermatitis"),
    ("Psoríase", "Placas", "intermediario",
     "{{sexWord}} de {{age}} com placas extensas refratárias ao tópico. Conduta?",
     "Avaliar fototerapia/sistêmico/biológico e rastrear artrite/metabólico",
     "Corticoide sistêmico prolongado de rotina sem plano", "AAD psoriasis"),
    ("Lúpus cutâneo", "Fotoproteção", "basico",
     "Mulher de {{age}} com LES e lesões fotossensíveis. Conduta?",
     "Fotoproteção + hidroxicloroquina e tratar lesões conforme extensão",
     "Banho de sol terapêutico diário", "EULAR SLE"),
    ("Raiva", "Exposição", "avancado",
     "{{sexWord}} de {{age}} mordido por cão suspeito sem vacina prévia. Conduta?",
     "Lavar ferida, vacina antirrábica ± IGR e avaliar animal",
     "Apenas pomada sem profilaxia", "WHO rabies"),
    ("Tétano", "Ferida", "basico",
     "{{sexWord}} de {{age}} com ferida contaminada e vacina duvidosa. Conduta?",
     "Limpeza, vacina (± soro) conforme status vacinal e ATB se indicado",
     "Nenhuma profilaxia tetânica em ferida profunda", "CDC tetanus"),
    ("Sepse", "Culturas", "basico",
     "{{sexWord}} de {{age}} com sepse. Sobre culturas?",
     "Coletar antes do ATB se não atrasar a 1ª dose; depois ATB imediato",
     "Atrasar ATB 6 h só para coletar culturas", "SSC"),
    ("Choque", "Distributivo", "intermediario",
     "{{sexWord}} de {{age}} com sepse, PAM baixa após volume. Conduta?",
     "Noradrenalina como vasopressor de primeira linha e reavaliar perfusão",
     "Dopamina em alta dose como preferência absoluta atual", "SSC"),
    ("IRA", "Pré-renal", "basico",
     "{{sexWord}} de {{age}} com diarreia, ureia/Cr altas e FENa baixa. Conduta?",
     "Reposição volêmica e suspender nefrotóxicos; reavaliar",
     "Diálise imediata em toda elevação de creatinina", "KDIGO AKI"),
    ("Hiponatremia", "Grave sintomática", "avancado",
     "{{sexWord}} de {{age}} com Na 112 e convulsão. Conduta?",
     "Bolus de SF 3% para interromper sintomas graves e depois correção controlada",
     "Correção lenta demais deixando convulsão sem tratar", "European hyponatremia"),
    ("Hipernatremia", "Hipovolêmica", "intermediario",
     "{{sexWord}} de {{age}} desidratado com Na 158. Conduta?",
     "Restaurar volume com cristaloides e depois corrigir água livre lentamente",
     "Água livre isolada em choque hipovolêmico sem restaurar perfusão", "Narrative electrolytes"),
    ("Hipercalemia", "ECG", "basico",
     "{{sexWord}} de {{age}} com K 7,1 e QRS alargado. Conduta?",
     "Cálcio IV para estabilizar membrana + shifts + remoção (diurético/binder/diálise)",
     "Apenas dieta sem medida de emergência", "AHA hyperK"),
    ("Acidose", "Metabólica AG", "avancado",
     "{{sexWord}} de {{age}} com pH 7,1, HCO3 6 e ânion gap alto. Conduta?",
     "Tratar causa (CAD/lactato/toxinas); bicarbonato só em cenários selecionados",
     "Bicarbonato empírico em massa sem diagnóstico", "Acid-base reviews"),
    ("Alcalose", "Metabólica", "intermediario",
     "{{sexWord}} de {{age}} com vômitos e HCO3 38. Conduta?",
     "Reposição de volume e cloreto (SF) + K; tratar a causa",
     "Acetazolamida em todo vômito sem avaliar volume", "Acid-base"),
    ("Distúrbio", "Misto", "avancado",
     "{{sexWord}} de {{age}} com DPOC e sepse: pH 7,35, pCO2 60, HCO3 32, AG alto. Conduta?",
     "Reconhecer alcalose metabólica/compensação + acidose metabólica agregada; tratar ambos",
     "Interpretar só pelo pH “quase normal” e ignorar gaps", "Acid-base"),
    ("Nutrição", "Refeeding", "avancado",
     "{{sexWord}} de {{age}} desnutrido inicia dieta e P cai a 1,0. Conduta?",
     "Reconhecer refeeding: repor P/Mg/K, tiamina e avançar dieta com cautela",
     "Dobrar calorias imediatamente sem eletrólitos", "ASPEN refeeding"),
    ("Nutrição", "Hospitalar", "basico",
     "{{sexWord}} de {{age}} internado com jejum prolongado. Conduta?",
     "Avaliar risco nutricional e iniciar suporte enteral precoce se possível",
     "Manter jejum absoluto por 14 dias sem plano", "ESPEN"),
    ("Cuidados", "Paliativos", "intermediario",
     "{{sexWord}} de {{age}} com doença avançada e dispneia refratária. Conduta?",
     "Aliviar sintoma (opioide titulado), comunicar e alinhar metas de cuidado",
     "Negar analgesia por “medo de viciar” em fim de vida", "NICE palliative"),
    ("Ética", "Consentimento", "basico",
     "{{sexWord}} de {{age}} recusa procedimento com capacidade preservada. Conduta?",
     "Respeitar recusa informada após explicar riscos/benefícios e alternativas",
     "Internar à força sem base legal/capacidade", "CFM ética"),
    ("Prevenção", "Câncer colo", "basico",
     "{{sexWord}} de {{age}} de 52 anos assintomático. Rastreio?",
     "Colonoscopia ou método validado conforme diretriz/idade/risco",
     "Nunca rastrear câncer colorretal", "USPSTF CRC"),
    ("Prevenção", "Mama", "basico",
     "Mulher de {{age}} na faixa de rastreio. Conduta?",
     "Mamografia conforme diretriz etária/risco e exame clínico",
     "RM anual obrigatória em risco populacional médio sem indicação", "USPSTF breast"),
    ("Prevenção", "Próstata", "intermediario",
     "Homem de {{age}} pergunta sobre PSA. Conduta?",
     "Decisão compartilhada sobre riscos/benefícios do rastreio",
     "Prostatectomia profilática em todo homem >50", "USPSTF PSA"),
]


def topics_count():
    return len(CM_WAVE2)
